name: Cypress Better Login Tests

on:
  workflow_dispatch:

jobs:
  cypress-better-login:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.12.2'

    - name: Install dependencies
      run: npm install

    - name: Run Cypress better login tests
      run: npm run cy:betterLogin
    
    - name: Upload report artifact
      uses: actions/upload-artifact@v2
      with:
        name: mochawesome-report
        path: cypress/reports/html/index.html
        retention-days: 30
        if-no-files-found: warn
      env:
        CI: true
